import {
  createEmptyBlock,
  newBlockId,
  type BlogBlock,
  type BlogBlockType,
} from "@/lib/blog-blocks";

export type InserterGroup = "texte" | "media" | "mise-en-page" | "widgets" | "embed";

export type BlogInserterItem = {
  id: string;
  type: BlogBlockType;
  label: string;
  description: string;
  group: InserterGroup;
  keywords: string[];
  icon: string;
  seed?: Partial<BlogBlock>;
};

export const INSERTER_GROUP_LABELS: Record<InserterGroup, string> = {
  texte: "Texte",
  media: "Médias",
  "mise-en-page": "Design",
  widgets: "Widgets",
  embed: "Embarqué",
};

function embedItem(
  id: string,
  label: string,
  provider: string,
  keywords: string[],
  icon: string,
): BlogInserterItem {
  return {
    id,
    type: "embed",
    label,
    description: `Coller une URL ${label}`,
    group: "embed",
    keywords: ["embed", provider, ...keywords],
    icon,
    seed: { type: "embed", url: "", caption: "", provider },
  };
}

export const BLOG_INSERTER_ITEMS: BlogInserterItem[] = [
  {
    id: "heading",
    type: "heading",
    label: "Titre",
    description: "Titre H1–H4",
    group: "texte",
    keywords: ["heading", "titre", "h2"],
    icon: "heading",
  },
  {
    id: "paragraph",
    type: "paragraph",
    label: "Paragraphe",
    description: "Texte courant",
    group: "texte",
    keywords: ["paragraph", "texte"],
    icon: "align-left",
  },
  {
    id: "list",
    type: "list",
    label: "Liste",
    description: "Puces ou numéros",
    group: "texte",
    keywords: ["list", "liste"],
    icon: "list",
  },
  {
    id: "quote",
    type: "quote",
    label: "Citation",
    description: "Citation classique",
    group: "texte",
    keywords: ["quote", "citation"],
    icon: "quote",
  },
  {
    id: "pullquote",
    type: "pullquote",
    label: "Citation mise en avant",
    description: "Citation large",
    group: "texte",
    keywords: ["pullquote"],
    icon: "text-quote",
  },
  {
    id: "code",
    type: "code",
    label: "Code",
    description: "Bloc de code",
    group: "texte",
    keywords: ["code"],
    icon: "code",
  },
  {
    id: "classic",
    type: "html",
    label: "Classique",
    description: "Zone de texte comme l’éditeur classique",
    group: "texte",
    keywords: ["classic", "html", "coller"],
    seed: { type: "html", content: "" },
    icon: "file-text",
  },
  {
    id: "image",
    type: "image",
    label: "Image",
    description: "Photo ou illustration",
    group: "media",
    keywords: ["image", "photo"],
    icon: "image",
  },
  {
    id: "gallery",
    type: "gallery",
    label: "Galerie",
    description: "Plusieurs images",
    group: "media",
    keywords: ["gallery", "carousel"],
    icon: "images",
  },
  {
    id: "cover",
    type: "cover",
    label: "Couverture",
    description: "Bannière avec titre",
    group: "media",
    keywords: ["cover", "banniere"],
    icon: "panel-top",
  },
  {
    id: "video",
    type: "video",
    label: "Vidéo",
    description: "MP4 ou YouTube",
    group: "media",
    keywords: ["video"],
    icon: "video",
  },
  {
    id: "audio",
    type: "audio",
    label: "Audio",
    description: "Fichier audio",
    group: "media",
    keywords: ["audio"],
    icon: "volume-2",
  },
  {
    id: "file",
    type: "file",
    label: "Fichier",
    description: "Lien de téléchargement",
    group: "media",
    keywords: ["file", "pdf"],
    icon: "file",
  },
  {
    id: "separator",
    type: "separator",
    label: "Séparateur",
    description: "Ligne de division",
    group: "mise-en-page",
    keywords: ["divider", "hr"],
    icon: "minus",
  },
  {
    id: "spacer",
    type: "spacer",
    label: "Espaceur",
    description: "Espace vertical",
    group: "mise-en-page",
    keywords: ["spacer"],
    icon: "move-vertical",
  },
  {
    id: "row",
    type: "columns",
    label: "Rangée",
    description: "2 colonnes",
    group: "mise-en-page",
    keywords: ["row", "rangee"],
    icon: "columns-2",
    seed: { type: "columns", count: 2, columns: ["Colonne 1…", "Colonne 2…"] },
  },
  {
    id: "columns",
    type: "columns",
    label: "Colonnes",
    description: "3 colonnes",
    group: "mise-en-page",
    keywords: ["columns", "grid"],
    icon: "columns-3",
    seed: { type: "columns", count: 3, columns: ["A…", "B…", "C…"] },
  },
  {
    id: "buttons",
    type: "buttons",
    label: "Boutons",
    description: "Appels à l’action",
    group: "mise-en-page",
    keywords: ["buttons", "cta"],
    icon: "rectangle-horizontal",
  },
  {
    id: "table",
    type: "table",
    label: "Tableau",
    description: "Tableau simple",
    group: "mise-en-page",
    keywords: ["table"],
    icon: "table",
  },
  {
    id: "group",
    type: "html",
    label: "Groupe",
    description: "Conteneur HTML",
    group: "mise-en-page",
    keywords: ["group", "groupe"],
    icon: "group",
    seed: { type: "html", content: "<div class=\"wp-block-group\">\n<p>Groupe…</p>\n</div>" },
  },
  {
    id: "countdown",
    type: "countdown",
    label: "Compte à rebours",
    description: "Date cible",
    group: "widgets",
    keywords: ["countdown"],
    icon: "timer",
  },
  {
    id: "progress",
    type: "progress",
    label: "Progression",
    description: "Barre de pourcentage",
    group: "widgets",
    keywords: ["progress"],
    icon: "gauge",
  },
  {
    id: "tabs",
    type: "tabs",
    label: "Onglets",
    description: "Contenu en onglets",
    group: "widgets",
    keywords: ["tabs"],
    icon: "app-window",
  },
  {
    id: "accordion",
    type: "faq",
    label: "Accordéon",
    description: "Questions / réponses",
    group: "widgets",
    keywords: ["accordion", "faq"],
    icon: "panel-bottom-open",
  },
  {
    id: "alert",
    type: "callout",
    label: "Alerte",
    description: "Encadré d’information",
    group: "widgets",
    keywords: ["alert", "callout"],
    icon: "triangle-alert",
    seed: { type: "callout", variant: "warning", title: "Alerte", content: "" },
  },
  {
    id: "iconbox",
    type: "iconbox",
    label: "Boîte icône",
    description: "Icône + texte",
    group: "widgets",
    keywords: ["iconbox"],
    icon: "box",
  },
  {
    id: "numberbox",
    type: "numberbox",
    label: "Boîte chiffre",
    description: "Chiffre + texte",
    group: "widgets",
    keywords: ["numberbox"],
    icon: "hash",
  },
  {
    id: "testimonial",
    type: "testimonial",
    label: "Témoignage",
    description: "Avis client",
    group: "widgets",
    keywords: ["testimonial"],
    icon: "message-circle",
  },
  {
    id: "pricing",
    type: "pricing",
    label: "Tarifs",
    description: "Offres et prix",
    group: "widgets",
    keywords: ["pricing"],
    icon: "badge-dollar-sign",
  },
  {
    id: "toc",
    type: "toc",
    label: "Sommaire",
    description: "Table des matières",
    group: "widgets",
    keywords: ["toc"],
    icon: "list-tree",
  },
  {
    id: "more",
    type: "more",
    label: "Lire la suite",
    description: "Coupe l’extrait",
    group: "widgets",
    keywords: ["more"],
    icon: "more-horizontal",
  },
  embedItem("embed", "Embarqué", "generic", ["embed"], "app-window"),
  embedItem("youtube", "YouTube", "youtube", ["youtube", "video"], "youtube"),
  embedItem("vimeo", "Vimeo", "vimeo", ["vimeo"], "video"),
  embedItem("instagram", "Instagram", "instagram", ["instagram"], "instagram"),
  embedItem("twitter", "X / Twitter", "twitter", ["twitter", "x"], "twitter"),
  embedItem("facebook", "Facebook", "facebook", ["facebook"], "facebook"),
  embedItem("spotify", "Spotify", "spotify", ["spotify"], "audio-lines"),
  embedItem("soundcloud", "SoundCloud", "soundcloud", ["soundcloud"], "cloud"),
  embedItem("flickr", "Flickr", "flickr", ["flickr"], "images"),
  embedItem("wordpress", "WordPress", "wordpress", ["wordpress"], "globe"),
  embedItem("maps", "Google Maps", "maps", ["maps", "carte"], "map-pin"),
  embedItem("gist", "GitHub Gist", "gist", ["gist", "github"], "github"),
  embedItem("tiktok", "TikTok", "tiktok", ["tiktok"], "video"),
  embedItem("reddit", "Reddit", "reddit", ["reddit"], "globe"),
  embedItem("ted", "TED", "ted", ["ted"], "video"),
  embedItem("tumblr", "Tumblr", "tumblr", ["tumblr"], "globe"),
  embedItem("kickstarter", "Kickstarter", "kickstarter", ["kickstarter"], "badge-dollar-sign"),
];

export function createBlockFromInserter(item: BlogInserterItem): BlogBlock {
  const base = createEmptyBlock(item.type);
  if (!item.seed) return base;
  return { ...base, ...item.seed, id: newBlockId(), type: item.type } as BlogBlock;
}
