FROM node:22-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends ffmpeg \
  && rm -rf /var/lib/apt/lists/* \
  && ffmpeg -version

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Vite inlines VITE_* at build time — Railway must pass these as service variables.
ARG VITE_SITE_URL=https://belkou.online
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_CONTACT_EMAIL
ARG VITE_WHATSAPP_PHONE
ARG VITE_WHATSAPP_GROUP_PREMIUM
ARG VITE_WHATSAPP_GROUP_VIP
ARG VITE_COHORT_START_DATE
ARG VITE_STATS_STUDENTS_BASE

ENV VITE_SITE_URL=$VITE_SITE_URL \
    VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_CONTACT_EMAIL=$VITE_CONTACT_EMAIL \
    VITE_WHATSAPP_PHONE=$VITE_WHATSAPP_PHONE \
    VITE_WHATSAPP_GROUP_PREMIUM=$VITE_WHATSAPP_GROUP_PREMIUM \
    VITE_WHATSAPP_GROUP_VIP=$VITE_WHATSAPP_GROUP_VIP \
    VITE_COHORT_START_DATE=$VITE_COHORT_START_DATE \
    VITE_STATS_STUDENTS_BASE=$VITE_STATS_STUDENTS_BASE

RUN test -n "$VITE_SUPABASE_URL" && test -n "$VITE_SUPABASE_ANON_KEY" \
  || (echo "ERROR: Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Railway before build." && exit 1)

RUN npm run build

ENV NODE_ENV=production

CMD ["npm", "run", "start"]
